export const browserCoreExamples = [
  "airabot browser status",
  "airabot browser start",
  "airabot browser stop",
  "airabot browser tabs",
  "airabot browser open https://example.com",
  "airabot browser focus abcd1234",
  "airabot browser close abcd1234",
  "airabot browser screenshot",
  "airabot browser screenshot --full-page",
  "airabot browser screenshot --ref 12",
  "airabot browser snapshot",
  "airabot browser snapshot --format aria --limit 200",
  "airabot browser snapshot --efficient",
  "airabot browser snapshot --labels",
];

export const browserActionExamples = [
  "airabot browser navigate https://example.com",
  "airabot browser resize 1280 720",
  "airabot browser click 12 --double",
  'airabot browser type 23 "hello" --submit',
  "airabot browser press Enter",
  "airabot browser hover 44",
  "airabot browser drag 10 11",
  "airabot browser select 9 OptionA OptionB",
  "airabot browser upload /tmp/airabot/uploads/file.pdf",
  'airabot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "airabot browser dialog --accept",
  'airabot browser wait --text "Done"',
  "airabot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "airabot browser console --level error",
  "airabot browser pdf",
];
